### ISSUE TITLE
start_polling()

### ISSUE THREAD

**Issue by mahrens61** [tschamm/boschshcpy#12]
If i am using the example from the front page i get the following error. 

Error in polling thread: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/lib/python3.9/dist-packages/boschshcpy/tls_ca_chain.pem. Waiting 15 seconds.
The short poll is working without error message.

All other used library call are working for me. Only long polling isn't working.
What i want to achieve is, i want to get a message if my Shutter change its state.

**Comment by tschamm** [comment]
please reopen, if it occurs again.
