### ISSUE TITLE
tls_ca_chain.pem fehlt bei der Installation durch pip

### ISSUE THREAD

**Issue by nixe64** [tschamm/boschshcpy#14]
Hallo Thomas,

ich bin begeistert von deiner Integration des Bosch SHC in Home Assistant. 

Allerdings musste ich die tls_ca_chain.pem manuell ins passende Verzeichniss meiner virtuellen Python-Umgebung kopieren, um sie starten zu können. Da es sich nicht um geschützte Informationen handelt und jeder diese öffentlichen Schlüssel auch bei Bosch bekommen kann, spricht meiner Ansicht nichts dagegen, sie in die Installation aufzunehmen.

Viele Grüße aus Bielefeld
Nixe

**Comment by nixe64** [comment]
Nochmals hallo,

bin noch nicht so lange in der Open Source Community tätig, deshalb hoffe ich, dass du mir vergibst, das ich nicht erst die offenen Issues durchgesehen habe.

ist die Lösung für Isue #12 

Nixe

**Comment by mahrens61** [comment]
Moin Nixe,
wo bekomme ich den öffentlichen Schlüssel tls_ca_chain.pem her ?

Gruß
Michael

**Comment by nixe64** [comment]
Moin Michael,

Sind bereits hier im Repository im Verzeichnis "boschshcpy".

Gruß
Nixe

**Comment by mahrens61** [comment]
Danke

**Comment by nixe64** [comment]
Bitte. Gern geschehen.
