### ISSUE TITLE
Bosch Smart Home Universalschalter flex WRC2

### ISSUE THREAD

**Issue by matzidp8** [tschamm/boschshcpy#25]
Hallo,

sorry das ich in deutsch schreibe. Aber mein Englisch ist nicht so gut.
Erst mal vielen Dank für die super Arbeit.

Ich hätte eine Frage, ist es möglich die Batterie Lichtschalter wie z.B. den **Bosch Smart Home Universalschalter flex WRC2 und den normalen Bosch Smart Home Universalschalter** mit zu integrieren?

Aktuell zeigt der Schalter bei Entitäten leider nur die Batterie an.
Schön wäre es, wenn als Entität auch die Schaltfunktion mit angezeigt werden würde.

Gruß
Matthias

**Comment by tschamm** [comment]
Das ist schon erfolgt. Wenn ein Schalter gedrückt wird, löst HA ein Event aus. Du kannst Automatisierungen erzeugen, welche auf die Events reagieren.  Dafür als Auslöser das Gerät wählen (WRC2), und als Auslöser den jeweiligen Event.
