### ISSUE TITLE
Migrate to API 2.1

### ISSUE THREAD

**Issue by sebastianharder** [tschamm/boschshcpy#4]
Support for API 1.0 is dropped, see BoschSmartHome/bosch-shc-api-docs#46

Migration to 2.1 is required.

**Comment by tschamm** [comment]
Thanks for pointing this out.

**Comment by sebastianharder** [comment]
@tschamm not sure if you support the intrusion detection system also, but there will be changes in the API being made public soon.

**Comment by tschamm** [comment]
@sebastianharder Yes I do, however from my tests the core functionality still works as expected with API 2.1. I will keep eyes open for upcoming changes.

**Comment by sebastianharder** [comment]
@tschamm API 2.1 is now available as Postman collection. Everything should still work after changing the api-version to 2.1 in the HTTP header. If you want to support the new intrusion detection profiles, the APIs are now available.
