### ISSUE TITLE
Failed to establish new connection

### ISSUE THREAD

**Issue by Typschke** [tschamm/boschshcpy#41]
Hello,

I'm running the API inside a thread of a flask app on a raspberry pi4 with bookworm/python 3.11. The thread calls every 10s a function which establishes a new session and reads out my sensors. This goes well for around two days, after that i get errors like these and my whole flask app fails:

> ERROR:root:Failed to get public information from SHC controller: HTTPSConnectionPool(host='smarthome-ip', port=smarthome-port): Max retries exceeded with url: /smarthome/public/information (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1c31eb10>: Failed to establish a new connection: [Errno 113] No route to host'))
> ERROR:root:Body: None
> ERROR:root:Headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': > 'keep-alive', 'api-version': '3.2', 'Content-Type': 'application/json'}
> ERROR:root:URL: https://smarthome-ip:smarthome-port/smarthome/information
> ERROR:root:Failed to get information from SHC controller: SHC Error (message: API call returned non-OK result (code 400)!: > b'<HTML><HEAD><TITLE>400</TITLE></HEAD><"BODY"><"H1">400 Unsupported HTTP Protocol Version: GETHTTP/1.1</H1></BODY></HTML>')

I tried to wrap i inside a try-except statement, so the thread would just try to reconnect endlessly and my flask app would still work, but these errors seem to be not handled in the except-clause.
I also tried to make one session at the start of my flask app and ether just start and stop polling in the function or just start polling and never stop, but the results are the same. 
Would you now what i do wrong? Why does it work for two days and then just crashes?

Best Regards

**Comment by tschamm** [comment]
Is this still occuring?

**Comment by Typschke** [comment]
Nope, my bad. I was using a python 3.9 venv somehow. Changed it to 3.11 and everything works fine again. Sorry for the trouble
